import { StyleSheet } from "react-native";
import { colors } from "../../constants/colors";
import { spacing, fontSize, borderRadius } from "../../constants/spacing";

export const solanaBridgeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.primary,
  },
  headerTitle: {
    fontSize: fontSize.lg,
    fontWeight: "600",
    color: colors.text.primary,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  networkBadge: {
    backgroundColor: colors.background.secondary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
  },
  networkBadgeText: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    fontWeight: "500",
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.full,
  },
  content: {
    flex: 1,
    padding: spacing.lg,
  },
  centerContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xl,
  },
  titleSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.xl,
  },
  title: {
    fontSize: fontSize.xl,
    fontWeight: "600",
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontSize: fontSize.md,
    color: colors.text.secondary,
  },
  amountCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
    alignItems: "center",
  },
  cardLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
  },
  amountValue: {
    fontSize: fontSize.xxl,
    fontWeight: "600",
    color: colors.text.primary,
  },
  feeCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  feeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.sm,
  },
  feeLabel: {
    fontSize: fontSize.md,
    color: colors.text.secondary,
  },
  feeValue: {
    fontSize: fontSize.md,
    color: colors.text.primary,
  },
  feeDeduction: {
    color: colors.accent.orange,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border.primary,
    paddingTop: spacing.sm,
    marginTop: spacing.sm,
  },
  totalLabel: {
    fontSize: fontSize.md,
    fontWeight: "600",
    color: colors.text.primary,
  },
  totalValue: {
    fontSize: fontSize.md,
    fontWeight: "600",
    color: colors.accent.green,
  },
  etaCard: {
    flexDirection: "row",
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    justifyContent: "space-between",
  },
  etaLabel: {
    fontSize: fontSize.md,
    color: colors.text.secondary,
  },
  etaValue: {
    fontSize: fontSize.md,
    color: colors.text.primary,
  },
  addressCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  addressLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
  },
  address: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontFamily: "monospace",
    lineHeight: 22,
    marginBottom: spacing.md,
  },
  copyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
  },
  copyText: {
    fontSize: fontSize.md,
    color: colors.text.accent,
    fontWeight: "500",
  },
  amountReminderCard: {
    backgroundColor: colors.accent.purple,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    alignItems: "center",
  },
  reminderLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  reminderAmount: {
    fontSize: fontSize.xl,
    fontWeight: "600",
    color: colors.text.primary,
  },
  infoCard: {
    flexDirection: "row",
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    gap: spacing.sm,
    alignItems: "center",
  },
  infoText: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    lineHeight: 18,
  },
  infoTextContainer: {
    flex: 1,
  },
  warningCard: {
    flexDirection: "row",
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  warningText: {
    flex: 1,
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  txInputContainer: {
    marginBottom: spacing.xl,
  },
  txInputLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
  },
  txInput: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontFamily: "monospace",
  },
  txInputHint: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    marginTop: spacing.xs,
  },
  primaryButton: {
    backgroundColor: colors.accent.purple,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
    marginBottom: spacing.md,
  },
  primaryButtonText: {
    fontSize: fontSize.md,
    fontWeight: "600",
    color: colors.text.primary,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.border.primary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
  },
  secondaryButtonText: {
    fontSize: fontSize.md,
    fontWeight: "500",
    color: colors.text.secondary,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  processingTitle: {
    fontSize: fontSize.xl,
    fontWeight: "600",
    color: colors.text.primary,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  processingSubtitle: {
    fontSize: fontSize.md,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.md,
  },
  processingHint: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    textAlign: "center",
  },
  successIcon: {
    marginBottom: spacing.xl,
  },
  successTitle: {
    fontSize: fontSize.xl,
    fontWeight: "600",
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  successSubtitle: {
    fontSize: fontSize.md,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.md,
  },
  successHint: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.xl,
  },
  instructionCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  instructionTitle: {
    fontSize: fontSize.md,
    fontWeight: "600",
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  instructionStep: {
    flexDirection: "row",
    marginBottom: spacing.sm,
  },
  stepNumber: {
    fontSize: fontSize.md,
    color: colors.accent.purple,
    fontWeight: "600",
    marginRight: spacing.sm,
    width: 20,
  },
  stepText: {
    flex: 1,
    fontSize: fontSize.md,
    color: colors.text.secondary,
    lineHeight: 22,
  },
  walletInfoCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  walletInfoLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
  },
  walletAddress: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontFamily: "monospace",
    fontWeight: "500",
  },
  confirmButton: {
    backgroundColor: colors.accent.green,
    marginTop: spacing.sm,
  },
  txHashContainer: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginTop: spacing.md,
    marginBottom: spacing.md,
    width: "100%",
  },
  txHashLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  txHashValue: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontFamily: "monospace",
  },
  operationContainer: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    width: "100%",
  },
  operationLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  operationValue: {
    fontSize: fontSize.sm,
    color: colors.text.primary,
    fontFamily: "monospace",
  },
  txInfoCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginVertical: spacing.md,
    width: "100%",
  },
  txInfoLabel: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  txInfoValue: {
    fontSize: fontSize.xs,
    color: colors.text.primary,
    fontFamily: "monospace",
    lineHeight: 18,
  },
  successNote: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    textAlign: "center",
    marginTop: spacing.md,
  },
});